### ISSUE TITLE
Always use separate scales for overlaid time series

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#107]
Feedback from Francis Zwiers: 

In the comparison "portals", when two variables that have the same units are displayed, they share a common scale (for example, prcptotETCCDI and rx1dayETCCDI). However, the range of values for those two variables may differ greatly, and the variable with the smaller range is compressed visually in the lower part of the graph. FZ says this makes it hard to understand the variations in the smaller-range variable, and to compare them, and this is clear once it's pointed out.

Suggested remedy: Always scale the variables separately (i.e., always use the right-hand scale as well). Sometimes they will differ on units, and sometimes share units but differ on range.

**Comment by corviday** [comment]
An example of a graph that would benefit from using separate scales (tropical nights versus icing days - Canada has very few tropical nights!):

![days](https://user-images.githubusercontent.com/4512605/48921431-9e949000-ee54-11e8-8c14-517c99ad9331.png)

I have, unfortunately, just located a comparison graph that is much harder to read with separate scales: tasmin + tasmax. They're parallel and end up drawn on top of eachother with separate scales.

Tasmin + tasmax with a shared scale:
![sharedaxis](https://user-images.githubusercontent.com/4512605/48921811-27143000-ee57-11e8-8441-5d07fab43548.jpg)

Tasmin vs tasmax with separate scales:
![screenshot from 2018-11-22 12-32-16](https://user-images.githubusercontent.com/4512605/48921813-30050180-ee57-11e8-8b7f-303343eea57a.png)


I wonder if there's a reasonably straightforward algorithm that could determine whather two variable should share a scale? Perhaps just if the maximum of one is greated than the minimum of the other.
