### ISSUE TITLE
Refactor MapController to encapsulate layer functionality

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#111]
The primary goal of this refactor is to make extending map functionality faster and easier. Encapsulating each displayed map layer (raster, isolines, station markers, any future map layers) along with its logic, callbacks, state, and controls as a child component of MapController means each new thing we'd like to display on the map can be added as a self-contained unit, instead of tying it into the current complex MapController logic.

A secondary goal is to support an eventual rearchitecture of the entire system to match react's best practices.

**Comment by rod-glover** [comment]
Resolved in #113
