### ISSUE TITLE
Use React Bootstrap Tabs component instead of react-bootstrap-tabs

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#129]
With the upgrade to React 16 and a recent version of React Bootstrap, react-bootstrap-tabs is no longer needed. We should substitute the React Bootstrap [Tabs](https://react-bootstrap.github.io/components/tabs/) component for it, and remove react-bootstrap-tabs as a dependency. Fewer dependencies better, and less maintenance as we continue to upgrade our tooling.

**Comment by jameshiebert** [comment]
Where are we using react-bootstrap-tabs?

**Comment by rod-glover** [comment]
Oops, I didn't pull before I looked at the code. More embarassing yet, I was the one who fixed it. Duh.
