### ISSUE TITLE
Climate Explorer Frontend treats "modtime" as a data-describing metadata attribute

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#131]
1.` util.shortestUniqueTimeseriesNamingFunction()`, which looks at how two datasets differ and creates a legend describing their differences, includes `modtime` in graph legends.

![modtimelegend](https://user-images.githubusercontent.com/4512605/36056959-d49531f0-0dbd-11e8-964d-93fc70b6f155.png)
--------
2.` DataControllerMixin.findMatchingMetadata()` can't find "matching" datasets; they don't "match" if their `modtime`s are different. Accordingly, seasonal and annual datasets matching a given monthly one can't be found, and a matching dataset with a different variable cannot be found for multivariable comparison.. The below graph _should_ show tasmax and tasmin, in all three time resolutions, but no dataset can be successfully matched to the monthly tasmax one, so it's the only one showing.
![notasmin](https://user-images.githubusercontent.com/4512605/36057006-4b900140-0dbe-11e8-9115-ddcad5cf0232.png)

**Comment by jameshiebert** [comment]
Arrrrrrg! Great catch :)
