### ISSUE TITLE
Add an extreme precipitation portal

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#134]
The extreme precipitation portal will display a specialized ensemble containing the variables pr, rx1day, rx5day, sdii, r10mm, r20mm, cwd, prcptot, r95pETCCDI, r99pETCCDI.

It will be generally similar to the comparison portal with pr always selected as the secondary variable, except for a few adjustments due to the fact that climatological means are available for pr, but not nominal time data, and vice versa for the extreme precipitation indices. A user selects a model, emissions scenario, and precipitation index. The portal shows:
- A map with pr as the secondary (isolines) variable, set by default to logarithmic scaling
- ~~A graph displaying the long term average for pr against the nominal values of the climate index~~
- A graph displaying Long Term Average for pr and climate indices
- ~~An Annual Cycle graph displaying pr values and letting users pick a climatology period as usual~~
- An Annual Cycle graph displaying pr and climate index values.

~~This design can be updated if/when climatological means for the extreme precipitation indices become available. Currently some of the extreme indices have separate monthly and annual variable names, so producing and naming climatological means for them would probably be somewhat messy.~~

**EDIT**: Update to reflect availability of climatologies for climdex data, which makes this portal much more straightforward. It will need its own `AppController` to handle variable selection, but can use a standard `DualDataController`, and either a standard or very lightly modified `MapController`.

**Comment by jameshiebert** [comment]
FYI, I think we're good to go ahead with producing climatological means of the ClimDEX variables.
