### ISSUE TITLE
Rename navigation tabs

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climate-explorer-frontend#142]
When I wrote the navigation tab functionality, I just put in place holder names. Unfortunately, they don't really have much meaning. "Climatology" is not exactly descriptive, since the entire tool provides climatological means.

We need to come up with labels for each tab that are actually succinct, descriptive and differentiate one view from the others.

**Comment by corviday** [comment]
I believe Trevor had suggestions about exactly that when I interviewed him about Climate Explorer. I'll check my notes.

**Comment by jameshiebert** [comment]
This was addressed by #156
