### ISSUE TITLE
Context graph doesn't notice changes of area

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#162]
The context graph makes several of of the most time-consuming API call (`/api/data`) to gather its data. Therefore, it is [clever](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/src/components/graphs/ContextGraph/ContextGraph.js#L91) about  when it needs to re-query the backend, and when it can just reformat data it already has. 

However, the algorithm for determining when to refetch and when to merely reformat is wrong. If the selected area changes, the context graph will reformat its data instead of fetching fresh data, but it actually needs to fetch fresh data in that case.

**Comment by jameshiebert** [comment]
That's a really good catch! Otherwise you may think that you're looking at data for one area and will actually be looking at data for another!
