### ISSUE TITLE
Improve UI for Future Anomaly graph

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#165]
Feedback from MOTI engineers indicates that the purpose and data of the Future Anomaly graph is unclear. Improve UI for this graph (title, graph labels, legend?) 

"Anomaly" might be a climate science word that isn't particularly meaningful to engineers; I was confused by its domain usage when I first got here.

**Comment by corviday** [comment]
I've experimented with expressing the anomaly as a percentage, rather than an absolute value, as I think someone mentioned during our conference call. 

While I agree showing the anomaly as a percentage change in addition to providing the raw numbers makes sense for precipitation data, it's extra screwy for temperature data or any other dataset that includes values near or below 0. For example, a change in a certain month from 0.1 degree celsius to 2 degrees celsius would be a +1900% change. Percentages seem less useful for temperature data.

Perhaps a toggle between percent and nominal change shown? Or maybe show percent if values are always higher than 0, otherwise show actual change?

Fairly clear percentage precipitation change:
![prpercent](https://user-images.githubusercontent.com/4512605/45574587-5ab65680-b825-11e8-9bf4-fd04e435364b.jpg)

Nonsensical temperature change:
![tasminpercent](https://user-images.githubusercontent.com/4512605/45574599-630e9180-b825-11e8-9df2-0b94947bcdcc.png)

Perhaps a "does this variable make sense as a percentage change" attribute in the variable configuration file?

**Comment by jameshiebert** [comment]
Generally temperature anomalies are *only* ever expressed as a nominal change and precip are *only* ever expressed as a percentage. We usually just have a variable->type mapping somewhere in the code and decide that way.

**Comment by corviday** [comment]
Thanks, that's a helpful convention to know! 

I'm leaning toward a units-based mapping. Units that count things, like millimeters of rain or days in a year, can have a change over time represented as a percentage change. Units that are scales, like temperature, or already percents, can't have a change over time represented as percentage.

**Comment by corviday** [comment]
On second thought, we already have a mechanism for "graphs/maps look slightly different depending on the variable shown" - [the variable configuration file](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/variable-options.yaml). Introducing a separate "graphs look slightly different depending on the units shown" system would be unnecessarily complicated. I'm just going to add an attribute for "anomalies for this variable should be expressed as a percentage" attribute to the variable configuration file.

**Comment by corviday** [comment]
Fixed by #180
