### ISSUE TITLE
"kg m-2 day-1" is not a user friendly unit for precipitation

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#169]
Both Trevor Murdock and MOTI engineers have indicated that while precipitation is often output as `kg m-2 d-1` from models, `mm/day` would be clearer to engineers, planners, and other non-climate-scientists.

One solution would be to add some sort of units attribute to the [variable configuration file](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/variable-options.yaml). Am advantage of this approach is that it would only apply to precipitation, which would be reasonable since measuring water is the only circumstances under which a kilogram per meter is equal to a millimeter.

[See also the back issue with precipitation units described here](https://github.com/pacificclimate/climate-explorer-backend/issues/83): that precip units are given by some files as `kg d-1 m-2` and others as `kg m-2 d-1`, which results in an error when trying to generate graphs with "different" units - which provides a reason to fix this issue on the back end instead.

**Comment by rod-glover** [comment]
Discussion with @corviday suggests that we could handle this by extending the variable configuration file to prescribe unit conversions.

It may also be the right solution to use the JS equivalent of pint to parse units so that we can abstract away from their multifarious string representations.
