### ISSUE TITLE
Anomalies should be calculated from a historical baseline

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climate-explorer-frontend#175]
We talked about this with MoTI, but it seems to have fallen off the RADAR. At present, the "future anomalies" plot calculates the anomaly from a future scenario (2020s) rather than using a historical baseline (1971-2000 or 1981-2010). The latter is the correct way to compute anomalies. This should be fixed before we launch.

**Comment by corviday** [comment]
Is there a preference for which of those two historical climatologies to use?
