### ISSUE TITLE
Stats not displayed for some CanESM2 climdices

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#176]
CanESM2 rcp85 tnnETCCDI, tnxETCCDI, txxETCCDI, and txnWTCCDI return the following error message on the stats table:

`selected[0] is undefined`

~~Possibly an instance of [this backend issue](https://github.com/pacificclimate/climate-explorer-backend/issues/83), which occurs when the backend attempts to aggregate data across files that use different units for the same variable. The four variables involved are among the handful known to have different units (`degC` vs. `degrees_C`), but I haven't verified this is the case.~~

**Comment by corviday** [comment]
```sql
SELECT DISTINCT 
  variable_aliases.variable_units, 
  models.model_short_name, 
  variable_aliases.variable_standard_name
FROM 
  ce_meta.ensembles, 
  ce_meta.ensemble_data_file_variables, 
  ce_meta.data_file_variables, 
  ce_meta.models, 
  ce_meta.data_files, 
  ce_meta.runs, 
  ce_meta.emissions, 
  ce_meta.variable_aliases
WHERE 
  ensembles.ensemble_id = ensemble_data_file_variables.ensemble_id AND
  ensemble_data_file_variables.data_file_variable_id = data_file_variables.data_file_variable_id AND
  data_file_variables.data_file_id = data_files.data_file_id AND
  data_file_variables.variable_alias_id = variable_aliases.variable_alias_id AND
  data_files.run_id = runs.run_id AND
  runs.model_id = models.model_id AND
  runs.emission_id = emissions.emission_id AND
  ensembles.ensemble_name LIKE 'ce_files' AND 
  models.model_short_name LIKE 'CanESM2' AND 
  variable_aliases.variable_standard_name LIKE 't%ETCCDI';
```

| variable_units | model_short_name | Variable_standard_name |
|----------------|------------------|------------------------|
| %              | CanESM2          | tn10pETCCDI            |
| degC           | CanESM2          | tnnETCCDI              |
| %              | CanESM2          | tc90ETCCDI             |
| degC           | CanESM2          | tnxETCCDI              |
| days           | CanESM2          | trETCCDI               |
| degC           | CanESM2          | txnETCCDI              |
| degC           | CanESM2          | txxETCCDI              |
| %              | CanESM2          | tx10pETCCDI            |
| %              | CanESM2          | tn90pETCCDI            |

Not a units issue.

**Comment by corviday** [comment]
Anecdotal observations have left me with the guess that the issue is the stats table is asking for monthly stats on annual-only datasets.

**Comment by rod-glover** [comment]
There's no variable `tc90ETCCDI`, but there is a `tx90ETCCDI`, which is not listed here. Assuming this is a typo.
