### ISSUE TITLE
Do we handle multiple polygons?

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#184]
The map tooling allows drawing any number of polygons. Do we use all of them?

If the answer is no: Should we allow multiple polygons and use all of them?

If we should allow and use only one polygon, then fix this feature so that only one can be drawn.

**Comment by corviday** [comment]
I thought we did, but I experimented with it just now, and it looks like only the most recently drawn polygon is passed to the backend.

**Comment by rod-glover** [comment]
MoTI has also remarked on this as follows:

>The app allows creating multiple polygons, in which case, it should allow selecting the polygon. And the selected Polygon should also be highlighted. Right now, in case of multiple polygons, not sure the graph and table represent which polygon.

**Comment by rod-glover** [comment]
The backend API (endpoints `timeseries` and `data`, specifically) receives geometry as WKT.

Our current GeoJSON utility cannot convert GeoJSON `FeatureCollection`s to WKT. It can however, convert a Feature of type `GeometryCollection` to WKT.

The backend API throws an error when given a Geometry Collection (WKT) as an `area` argument (query param).

**Comment by rod-glover** [comment]
Allowing multiple polygons may have been either an intentional, active choice or a passive result of the fact that the tools automatically support it. 

It's not made explicit anywhere in comments whether this choice was intentional. The backend does not handle one case (Geometry Collection) of multiple polygons. This suggests the original intention was (through a quite possibly passive choice) to support only single polygons.

In the absence of any explicit indications, there are a few reasonable options open to us:

1. Disallow multiple polygons in the frontend. 
   1. This will be easy, except in the case of importing a multi-polygon file, in which case we will have to decide how to handle it. Options:
      1. Default to current first-geometry-only behaviour. Should add a warning message/dialog. Most flexible, since user can delete all but single desired geometry.
      1. Filter out all but the first item in a multi-feature/geometry. Should add a warning message/dialog.
      1. Disallow multi-feature/geometry uploads. Should add an explanatory message/dialog.
   1. This is likely the simplest, lowest-effort option.

1. Allow multiple polygons but enable the user to select which one is active, i.e., which one is used for spatial averaging.
   1. In principle simple, but not supported by any tool yet. This could (and probably) will require significant effort to implement (unless there is an out of the box selector tool that is easily compatible with our current code).

1. Allow multiple polygons and treat them a single, joint (or union) area selection. 
   1. This will require fixing the backend to handle a multi-feature `area` argument.
   1. Disadvantages:
      1. Does it make any physical sense to spatially average over separated (disjoint, non-adjacent) areas? Likely not. But the tool would allow this without a really large amount of extra complication and coding effort.
      1. What do we do about overlapping polygons? Perform a spatial union on them (presumably on the backend)? Disallow them (presumably on the frontend)? In either case this would require considerable  extra effort in analysis and coding.
   1. Advantages: 
      1. Handles this scenario: Several adjacent areas that a user wishes to have treated as single area, i.e., as their (disjoint) union. For example, two or more adjacent watersheds, for which the user has existing geometry files they can upload (or a single multi-feature/multi-geometry file). Note: This could be handled externally by asking the user to create using external tools a single feature geometry file.
   1. This is likely the most complicated, highest-effort option.

**Comment by corviday** [comment]
I can't think of a use case where someone would want multiple polygons offhand. I'd be inclined to not support multiple polygons until someone requests them.

**Comment by rod-glover** [comment]
I agree. I will email Jim Barnes and to let him know our view and ask his opinion, as promised.

**Comment by rod-glover** [comment]
Jim Barnes has not replied. For the present, we will allow only one polygon to be drawn. If more than one polygon is imported (e.g., from a file containing a GeoJSON FeatureCollection or from multiple imports), then only the first (in order of importation) will be "active", meaning that only the first will be used to form spatial data averages and also will be the only one to be exported using the map Export polygon tool.
