### ISSUE TITLE
Statistical Summary allows user to select invalid Time of Year

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#215]
To reproduce:

1. Home/Data > Single Variable
1. Select Model = CanESM2; Emissions Scenario = historical, rcp85; Variable = altwsdiETCCDI
1. In Statistical Summary table, Time of Year selector includes all values, but only Annual is valid. All other selections show an error message at the bottom, but keep displaying the annual value. 

The ToY selector should only show valid selections. General UI rule: Don't offer a user an invalid course of action.

**Comment by corviday** [comment]
Related enough it should probably be handled in the same PR: https://github.com/pacificclimate/climate-explorer-frontend/issues/193

**Comment by corviday** [comment]
Probably also the cause of [this issue](https://github.com/pacificclimate/climate-explorer-frontend/issues/176).

**Comment by rod-glover** [comment]
@corviday suggests cause: Stats table needs an algorithm parallel to the one for graphs that matches datasets on time resolution. ToY selector needs to (be fed data that):

1. Show all and only valid time resolutions.
1. Select a valid default.

Stats table needs first to be refactored into its own component first, to give this logic a legitimate place to live.

Addressing this should fix all 3 of these issues.
