### ISSUE TITLE
Switching variables may result in invalid selected climatologies

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#219]
To reproduce:

1. Select a dataset that has a 1961-1990 climatology, such as CanESM, rcp85, tasmax.
2. Switch to a dataset that _doesn't_ have a 1961-1990 climatology, such as CanESM, rcp85, cdd.

The 1961-1990 climatology will remain selected, despite not being present in the new data selection:
* climatology selector for relevant graphs will display `{"start_date":1961, "end_date": 1990, "run": "r1i1p1"}` 
* graphs will display "No data to show" error message

This is a newly-uncovered problem that affects the Degree Day and Return Period data, which are available for a different set of climatologies than the Climdex and Downscaled data. These datasets have only 4 climatologies each.

**Comment by rod-glover** [comment]
Does our current code (attempt to) preserve the climatology selection between datasets? It would seem so.

If so, the questions are 

1. Is this preservation desirable?
1. Would it be better to reset the climatology selection (to, say, the earliest one available for the dataset) whenever a different dataset is selected?
1. If there is a convincing argument for preserving selection, then we need to do the item above when there is no matching climatology for the selected dataset.

**Comment by rod-glover** [comment]
Closed duplicate

**Comment by rod-glover** [comment]
Closed wrong one

**Comment by corviday** [comment]
The current code preserves the selected climatology pretty much by default: it just doesn't update the chosen period in state when the user switches variables. I think that's reasonably intuitive behaviour, though it needs patched to handle the case when there isn't a matching climatology. 

I could also see an argument for always displaying the earliest period when switching variables, or always displaying the current period when switching variables.

I don't think users would have trouble following any of those strategies, whichever we decided to apply.
