### ISSUE TITLE
Some variables have annual and monthly/seasonal values presented separately

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#224]
The following variables

- `rx1day`
- `rx5day`
- others??

are presented in the Single Variable and Compare Variables views in the following way:

- The annual and monthly versions of the variable  (as computed by RCI and used by us) have the same name but are listed separately in the dropdown with different long-form names/explanations to distinguish them.
- The monthly and annual versions appear far apart in the dropdown list.
- The annual version
   - is apparently a time series, with a value for every year from 1950-2100
   - is therefore presented in a Time Series graph only
   - is labelled ambiguously in the value popover as "yearly mean" (see fixes below)
- The monthly version
  - is apparently a climatological dataset
  - is therefore presented in Annual Cycle Graph, Long Term Average, Model Context, Change From Baseline, Snapshot
  - has seasonal values (computed how?) for only two of the 8 datasets 
  - has yearly values for none of the 8 datasets

This is very confusing for at least the following reasons:

1. The annual and monthly versions of the variable are far apart in a long list of dropdown options and therefore it is not apparent that the other exists.
1. The two closely related variables, `rx1day` and `rx5day` (in their monthly and annual versions), are also presented far apart in the dropdown options.
1. Only the kind(s) of graph presented when you choose the variable indicate that one is a long-term time  series while the other is climatological means. There's no indicator and no explanation for this difference.
1. The climatological dataset collection is incomplete.
1. I am a fairly sophisticated user of this app, and it took me several minutes to work out what is going on here.

Suggested fixes:

1. Order the list so that these variables appear as adjacent options in the dropdown as follows: rx1day annual, rx1day monthly, rx5day annual, rx5day monthly.
1. Provide an indicator in each variable's label (i.e., dropdown option) of whether it is a climatology or time series (man, I hate that usage of the latter term, but it's what we've got for now). This is probably worth doing generically, i.e., adding something to the variable name/description that indicates whether it is a climatology or a time series.
1. Complete the climatological datasets.
1. Alter the labels in the Annual Cycle Graph to express "multi-year mean of monthly maximum" (AND we must ensure that this is actually a true statement, but that's a data issue, TBD)

**Comment by rod-glover** [comment]
Related issue: #216

**Comment by corviday** [comment]
```sql
SELECT DISTINCT
  variable_aliases.variable_standard_name, 
  time_sets.multi_year_mean
FROM 
  ce_meta.data_files, 
  ce_meta.time_sets, 
  ce_meta.data_file_variables, 
  ce_meta.variable_aliases, 
  ce_meta.ensembles, 
  ce_meta.ensemble_data_file_variables
WHERE 
  data_files.time_set_id = time_sets.time_set_id AND
  data_file_variables.variable_alias_id = variable_aliases.variable_alias_id AND
  data_file_variables.data_file_id = data_files.data_file_id AND
  ensemble_data_file_variables.data_file_variable_id = data_file_variables.data_file_variable_id AND
  ensemble_data_file_variables.ensemble_id = ensembles.ensemble_id AND
  ensembles.ensemble_name LIKE 'ce_files'
ORDER BY
  variable_standard_name;
```

| variable_standard_name | multi_year_mean | variable_long_name                                                                                       |
|------------------------|-----------------|----------------------------------------------------------------------------------------------------------|
| air_temperature        | t               | Daily Maximum Near-Surface Air Temperature                                                               |
| air_temperature        | t               | Daily Minimum Near-Surface Air Temperature                                                               |
| altcddETCCDI           | f               | Maximum Number of Consecutive Days Per Year with Less Than 1mm of Precipitation                          |
| altcsdiETCCDI          | f               | Cold Spell Duration Index Spanning Years                                                                 |
| altcwdETCCDI           | f               | Maximum Number of Consecutive Days Per Year with At Least 1mm of Precipitation                           |
| altwsdiETCCDI          | f               | Warm Spell Duration Index Spanning Years                                                                 |
| cddETCCDI              | f               | Maximum Number of Consecutive Days with Less Than 1mm of Precipitation                                   |
| cooling_degree_days    | t               | Cooling Degree Days (Threshold: 18C)                                                                     |
| csdiETCCDI             | f               | Cold Spell Duration Index                                                                                |
| cwdETCCDI              | f               | Maximum Number of Consecutive Days with At Least 1mm of Precipitation                                    |
| dtrETCCDI              | f               | Mean Diurnal Temperature Range                                                                           |
| dtrETCCDI              | t               | Mean Diurnal Temperature Range                                                                           |
| fdETCCDI               | f               | Number of Frost Days                                                                                     |
| freezing_degree_days   | t               | Freezing Degree Days (Threshold: 0C)                                                                     |
| growing_degree_days    | t               | Growing Degree Days (Threshold: 5C)                                                                      |
| gslETCCDI              | f               | Growing Season Length                                                                                    |
| heating_degree_days    | t               | Heating Degree Days (Threshold: 18C)                                                                     |
| idETCCDI               | f               | Number of Icing Days                                                                                     |
| prcptotETCCDI          | f               | Annual Total Precipitation in Wet Days                                                                   |
| precipitation_flux     | t               | Precipitation                                                                                            |
| r10mmETCCDI            | f               | Annual Count of Days with At Least 10mm of Precipitation                                                 |
| r1mmETCCDI             | f               | Annual Count of Days with At Least 1mm of Precipitation                                                  |
| r20mmETCCDI            | f               | Annual Count of Days with At Least 20mm of Precipitation                                                 |
| r95pETCCDI             | f               | Annual Total Precipitation when Daily Precipitation Exceeds the 95th Percentile of Wet Day Precipitation |
| r99pETCCDI             | f               | Annual Total Precipitation when Daily Precipitation Exceeds the 99th Percentile of Wet Day Precipitation |
| rp20pr                 | t               | 20-year annual maximum one day precipitation amount                                                      |
| rp20tasmax             | t               | 20-year annual maximum daily maximum temperature                                                         |
| rp20tasmin             | t               | 20-year annual minimum daily minimum temperature                                                         |
| rp50pr                 | t               | 50-year annual maximum one day precipitation amount                                                      |
| rp5pr                  | t               | 5-year annual maximum one day precipitation amount                                                       |
| rp5tasmax              | t               | 5-year annual maximum daily maximum temperature                                                          |
| rp5tasmin              | t               | 5-year annual minimum daily minimum temperature                                                          |
| rx1dayETCCDI           | f               | Annual Maximum 1-day Precipitation                                                                       |
| rx1dayETCCDI           | t               | Monthly Maximum 1-day Precipitation                                                                      |
| rx5dayETCCDI           | f               | Annual Maximum Consecutive 5-day Precipitation                                                           |
| rx5dayETCCDI           | t               | Monthly Maximum Consecutive 5-day Precipitation                                                          |
| sdiiETCCDI             | f               | Simple Precipitation Intensity Index                                                                     |
| suETCCDI               | f               | Number of Summer Days                                                                                    |
| tn10pETCCDI            | f               | Percentage of Days when Daily Minimum Temperature is Below the 10th Percentile                           |
| tn10pETCCDI            | t               | Percentage of Days when Daily Minimum Temperature is Below the 10th Percentile                           |
| tn90pETCCDI            | f               | Percentage of Days when Daily Minimum Temperature is Above the 90th Percentile                           |
| tn90pETCCDI            | t               | Percentage of Days when Daily Minimum Temperature is Above the 90th Percentile                           |
| tnnETCCDI              | f               | Annual Minimum of Daily Minimum Temperature                                                              |
| tnnETCCDI              | t               | Monthly Minimum of Daily Minimum Temperature                                                             |
| tnxETCCDI              | f               | Annual Maximum of Daily Minimum Temperature                                                              |
| tnxETCCDI              | t               | Monthly Maximum of Daily Minimum Temperature                                                             |
| trETCCDI               | f               | Number of Tropical Nights                                                                                |
| tx10pETCCDI            | f               | Percentage of Days when Daily Maximum Temperature is Below the 10th Percentile                           |
| tx10pETCCDI            | t               | Percentage of Days when Daily Maximum Temperature is Below the 10th Percentile                           |
| tx90pETCCDI            | f               | Percentage of Days when Daily Maximum Temperature is Above the 90th Percentile                           |
| tx90pETCCDI            | t               | Percentage of Days when Daily Maximum Temperature is Above the 90th Percentile                           |
| txnETCCDI              | f               | Annual Minimum of Daily Maximum Temperature                                                              |
| txnETCCDI              | t               | Monthly Minimum of Daily Maximum Temperature                                                             |
| txxETCCDI              | f               | Annual Maximum of Daily Maximum Temperature                                                              |
| txxETCCDI              | t               | Monthly Maximum of Daily Maximum Temperature                                                             |
| wsdiETCCDI             | f               | Warm Spell Duration Index                                                                                |

So it looks like variables that _could_ conceivably have this problem are:
- dtrETCCDI 
- rx1dayETCCDI
- rx5dayETCCDI
- tn10pETCCDI
- tn90pETCCDI
- tnnETCCDI
- tnxETCCDI
- tx10pETCCDI
- tx90pETCCDI
- txnETCCDI
- txxETCCDI

**Comment by rod-glover** [comment]
To uncover the root cause, we need to trace the origins and computations that produce the climatologies we are displaying.

**Comment by rod-glover** [comment]
The above are the variables which would need the distinction shown between long-term time series and climatologies.

**Comment by rod-glover** [comment]
See also #216 for one of the suggested fixes (different way of selecting variable).

**Comment by corviday** [comment]
This issue has been resolved at the source; the data irregularities are resolved.
