### ISSUE TITLE
Erroneous content shows in Annual Cycle graph Dataset dropdown for some variables

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#226]
Instead of a valid climatological time period being shown in the Annual Cycle graph Dataset dropdown, a JSON object is displayed.

This occurs for the following variables:

- `cdd`
- `fdd`
- `gdd`
- `hdd`
- `rp20pr`
- `rp50pr`
- `rp5pr`
- `rp20tasmax`
- `rp5tasmax`
- `rp20tasmin`
- `rp5tasmin`

and no others, as far as I can tell.

To reproduce:

1. Go to or refresh Single Variable view
1. Select Variable = one the variables listed above 
1. In Annual Cycle graph 
    - Dataset selector shows a JSON object
    - Graph shows message "No data to show"

Notes: 

1. JSON object is not really an option; it does not appear in the drop down and disappears if you select a real option from the dropdown.
1. For the return period variables, you have to start with a "fresh" page for this to happen. If you select another variable before selecting one of the offending ones, the JSON object doesn't appear. 
1. If you see the JSON object, then select a valid option, then select a different offending variable, the JSON object doesn't appear.

**Comment by corviday** [comment]
https://github.com/pacificclimate/climate-explorer-frontend/issues/219

**Comment by rod-glover** [comment]
Closed duplicate
