### ISSUE TITLE
Update README to reflect new run variable procedure

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#243]
Previously, a number of variables for climate explorer were either set in the shell environment, or fell back to default values set in [webpack.config.js](https://github.com/pacificclimate/climate-explorer-frontend/blob/590a97e8767b799d55e9f57ee2f1c789933f9b0c/webpack.config.js), which were used if the user hadn't set them in the shell environment (ie, by running `export CE_ENSEMBLE_NAME="ce_files" ` in the shell). 

#236 updates climate explorer to take these variables from [package.json](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/package.json) instead of the environment or webpack.config.js.

[README.md](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/README.md) needs to be updated to reflect the new procedure: setting these variables via package.json instead of the environment. 

Possibly either update Dockerfile or include some documentation on how a developer would set those variables in a docker container if they do not want to use the defaults provided by package.json. (For example, if they were setting up a frontend docker to use a test backend instead of the live one.)

Possibly update webpack.config.js to remove the previous default values.

**Comment by rod-glover** [comment]
My mistake. I should not have committed that; or better I should have defined a new npm script that invokes `npm start` this way. I'll fix this.

There's also a complication here: `npm start` runs the app in the test environment (`NODE_ENV=test`). [We almost certainly shouldn't be doing this.](https://github.com/pacificclimate/climate-explorer-frontend/issues/282) If we were not running a test environment for production, then this mistake wouldn't cause problems for production deploys. However it would still be inconvenient for those of us testing with different settings than @rod-glover prefers!

**Comment by corviday** [comment]
This was resolved by #283
