### ISSUE TITLE
Var 1 = pr, Var 2 = cdd => no isoline (Var 2) layer on map

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#260]
To reproduce:

1. Go to Compare Variables view.
1. Default variables are Var 1 = pr, Var 2 = pr.
1. In Variable 2, select cdd.
1. No cdd layer appears. Verify this by turning off the raster (Variable 1; pr) layer.

However, the opposite order of variables does not produce this error: Selecting Var 1 = cdd, Var 2 = pr causes both layers to appear on the map.

**Comment by corviday** [comment]
This is the map-related manifestation of teh graph bug https://github.com/pacificclimate/climate-explorer-frontend/issues/219, which I for some reason hadn't realized would happen.

**Comment by rod-glover** [comment]
Oops, this is a known behaviour, and is even flagged by the message "cdd not available for this time period" in the map legend. 

This is a function of there being only 4 climatologies for degree-day variables and 6 climatologies for variables like pr. When pr is selected as Variable 1, its default dataset (1961-1990) does not match any available cdd dataset, and so the observed behaviour. Conversely, when cdd is selected as Variable 1, its default dataset (1971-2000) does match a pr dataset.

This is still not really desirable behaviour, and it has one or more solutions:

1. Ask RCI to produce the missing climatologies for degree-day datasets.
1. Default selection of datasets based on intersection of the available datasets for both variables, rather than the Variable 1 only based default presently used.

**Comment by rod-glover** [comment]
@corviday , re. #219, I think not really, though it is a cousin.

1. The map dataset selector does not display the erroneous value exhibited in #219, even when the graph dataset selector does.
1. The issue manifests only in comparison view.

**Comment by corviday** [comment]
While this is no longer true of cdd, fdd, gdd, and hdd, which have had shiny new data added, it is still true of the return period datasets.

**Comment by rod-glover** [comment]
Alert the user to the situation with a modal dialog or some other more apparent notification.

**Comment by corviday** [comment]
Presently this behaviour can be triggered by selecting `pr` as Variable 1, and any return period variable as Variable 2. We're missing a bunch of return period climatologies.

**Comment by corviday** [comment]
The return period data has been updated, and as far as I know, it is not currently possible to trigger this error.

**Comment by rod-glover** [comment]
Can we close this issue then?

**Comment by corviday** [comment]
Yeah, I think so. The [possible solutions](https://github.com/pacificclimate/climate-explorer-frontend/issues/260#issuecomment-447077490) to this issue were:

>     1. Ask RCI to produce the missing climatologies for degree-day datasets.
> 
>     2. Default selection of datasets based on intersection of the available datasets for both variables, rather than the Variable 1 only based default presently used.

We've now done the former, and the latter has [its own issue](https://github.com/pacificclimate/climate-explorer-frontend/issues/266) if we still wish to pursue it, though I imagine it's going to be a low priority in the absence of datasets that trigger it.
