### ISSUE TITLE
Displayed run identifiers are not user friendly

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#275]
When users select a dataset to view in the Annual Cycle graph, the options will be something like:

```
r1i1p1 1961-1990
r1i1p1 1971-2000
r1i1p1 1981-2010
r1i1p1 2010-2039
r1i1p1 2040-2069
r1i1p1 2070-2100
```

Users don't know or care about the run, and including it in the dropdown implies it's something they _should_ know or care about. It should be removed or replaced.

**Comment by rod-glover** [comment]
I have a solution for this already built in the new selectors. Please don't spend time on this: it will be unnecessary. Installing the new selectors is a priority for me, following immediately after getting the videos completed. Assigning this to myself just to emphasize the point.

**Comment by rod-glover** [comment]
Fixed
