### ISSUE TITLE
Reconsider the use of the word "Mean" in data series labels

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#277]
Currently, each data series on a chart is labeled with a dynamically generated series of attributes drawn from the dataset metadata, followed by the word "Mean." Such as: 
- Yearly Mean
- Tasmax Mean
- Yearly Tasmax Mean
- Tasmax 2010-2039 Mean

The word "Mean" is hard coded; everything else is derived from comparing the metadata for each dataseries and including each attribute (resolution, variable, period, etc) which varies between timeseries in the legend.

However, I think there are some variables, specifically return period datasets and degree day datasets, where the hardcoded "Mean" might not be the clearest possible phrasing.. It's not technically inaccurate - these data series still represent climatological means - but it seems less obvious that this is the right phrasing than for datasets like tasmax or tasmin, which represent the climatological means of monthly or seasonal means of a daily dataset. 

I'd like to ask Trevor if he has any better ideas for dataset labels, and if so, implement them. He may not, though, which isn't a big deal - detailed descriptions of what variables represent is available in the help. It may not be possible to improve on the short summary in the legends.

Low priority.

**Comment by corviday** [comment]
"Count" might work. Degree days would say "Annual Count", "Seasonal Count", and "Monthly Count" instead of "Annual Mean," "Seasonal Mean," and "Monthly Mean."

**Comment by rod-glover** [comment]
I see your point, and at the same time I fear that losing the information (or hint of the information) that these are climatological means will be more confusing. "Mean Count" would convey it, but perhaps that is too long?

**Comment by corviday** [comment]
I'll experiment with "Mean Count" and see how it looks.
