### ISSUE TITLE
s/Climate Explorer/PCIC Climate Explorer/g

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climate-explorer-frontend#285]
There are a couple of spots, including a very prominent one [here](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/src/components/App/App.js#L146) where "Climate Explorer" should be referred to as "PCIC Climate Explorer (PCEX)". This is a blocker for release and needs to be corrected.

**Comment by rod-glover** [comment]
Forgot to auto-close from PR.
