### ISSUE TITLE
Annual Cycle data selection dropdown displaying incorrect choices

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#325]
Some weirdness with the Annual Cycle graph's dataset selection dropdown:

1. When PCEX first opens, initially loading the PCIC12 pr dataset, the dropdown displays `{'start_date': '1971', 'end_date': '2000', 'ensemble_member': 'rXi1p1'}` instead of `1971-2000 rXi1p1`

2. When another model / variable / experiment is selected, the dropdown displays only the 1961-1990 option.

This bug is not yet present on the live deployed version, but should certainly be fixed before our next deploy.

**Comment by rod-glover** [comment]
Possibly related to #326
