### ISSUE TITLE
Optionally disable scroll wheel zooms

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climate-explorer-frontend#369]
From Francis:

> ...there is also an aspect of the way the maps interact with the
>    mouse on my machine that I find frustrating and that seems to be generic
>    to most sites that display maps (e.g., Google maps does the same thing).
>    Specifically, I have an Apple Magic Mouse that has a touch pad on its back
>    instead of a scroll wheel. The map zoom control probably works really well
>    with the scroll wheel, but controlling the map zoom level with the touch
>    pad (you slide a finger up and down to scroll) in a sensible way is
>    virtually impossible (every gesture leads to zooming in or out way too
>    much).

I find this when I'm on a laptop with a touchpad and it's *super* irritating. There are a variety of scroll wheel settings in leaflet. We could either provide a check box to disable the [`scrollwheelzoom`](https://leafletjs.com/reference-1.6.0.html#map-scrollwheelzoom), or possibly tweak the [`wheelDebounceTime`](wheelDebounceTime) to be less sensitive.

**Comment by rod-glover** [comment]
Great feedback. I'll copy this issue to Plan2Adapt too.

**Comment by rod-glover** [comment]
Superseded by #373
