### ISSUE TITLE
lint script missing

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#406]
The README says `npm run lint` can be used to lint files, but this does not work for me.

``` bash
$ npm run lint
npm ERR! missing script: lint

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lzeman/.npm/_logs/2021-04-23T14_50_15_037Z-debug.log
```

**Comment by Nospamas** [comment]
Updated as part of #460. Swapped out eslint in favour of prettier. `npm run lint` and `npm run format` will now give warnings and automatically fix. Updated docs to reflect this.
