### ISSUE TITLE
Add AppControllers for CMIP6 data

### ISSUE THREAD

**Issue by eyvorchuk** [pacificclimate/climate-explorer-frontend#416]
Now that `pr`, `tasmin`, and `tasmax` climatological means for the CMIP6 data have been added to the `ce_meta_12f290b63791` database, new `AppControllers` should be created so that this data can be interacted with.

**Comment by rod-glover** [comment]
Are you suggesting that the CMIP6 data should be presented separately from the CMIP5 data? If so, what is the reasoning for this?
