### ISSUE TITLE
clean up code style issues

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#436]
eslint is run automatically when starting up in a container, and outputs a lot of code style issue warnings. They'll probably be pretty quick to tidy up.

**Comment by aliwhosane** [comment]
@corviday I have worked on this issue and was able to remove the majority of warnings. Kindly have a look at the pull request https://github.com/pacificclimate/climate-explorer-frontend/pull/445

I am new to contributing to the open source community, do forgive me if I have not followed any unsaid rule or have done something I wasn't supposed to do.

**Comment by Nospamas** [comment]
Used @aliwhosane's branch as a basis for #460. Closing this issue as completed now that the changes have been merged in.
