### ISSUE TITLE
Datagraph y-axis number formatting on MOTI portal

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#48]
![screenshot from 2017-05-29 10-33-48](https://cloud.githubusercontent.com/assets/4512605/26793657/a4346fa2-49d3-11e7-85e9-255414e74580.png)

Not sure why this happens yet; it looks like the `DataGraph` props are the same on the `MotiDataController` component as the `DataController` component, but I haven't see this behaviour with `DataController`.

**Comment by jameshiebert** [comment]
This is basically a problem with the DataController asking for and receiving the wrong type of data (or at least not checking what type of data it's asking for).

It's getting a 17-point seasonal climatology (i.e. 12 months + 4 seasons + 1 annual), but it's trying to display it as timeseries plot (which it shouldn't).

I think the solution to this is having the DataController check the metadata more carefully.

**Comment by corviday** [comment]
Sorry for being unclear, I actually just meant this issue to refer to the formatting for y axis values, such as `12.2000000000000001` when `12.2` seems sufficiently precise.

**Comment by jameshiebert** [comment]
Ahhh, yep that's a problem :)
