### ISSUE TITLE
Test and refine DataController layout on small screens

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#70]
The Download Data controls and the Select Time of Year controls seemed to render on top of each other on a low-resolution laptop screen. Should look into that and if necessary adjust the [bootstrap Grid](https://v4-alpha.getbootstrap.com/layout/grid/) parameters (separate layouts for small, medium, and large screens)  to make that work better.

**Comment by corviday** [comment]
Matthew says:

> I just noticed that the map on the current climate explorer page doesn't seem to be autoscaling - it's fixed. So when viewing on smaller screens it floats over top of the other content.
> 
> It looks like the map has been fixed at 890 x 700px

**Comment by rod-glover** [comment]
Fixed
