### ISSUE TITLE
DualDataController selector does not change

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climate-explorer-frontend#78]
I think that PR #73 may have introduced a bug to the "instance" Selector. The instance shown in the selector is stuck on the first entry.

Steps to reproduce:
1. See the deployment of pcic/climate-explorer-frontend:latest [here](http://docker2.pcic.uvic.ca:9998/compare)
1. Choose the "Annual cycle" plot
1. In the plot selector, select a "Dataset" that is not the first in the list (e.g. 'r1i1pi 2070-2099')

Expected result:
'r1i1pi 2070-2099' will be selected

Actual result:
The first element in the list (in this case 'r1i1p1 1961-1990') is selected

I'm guessing that it's a problem with [line 233 in the render function](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/src/components/DualDataController/DualDataController.js#L233), but I'd be grateful if you could investigate.

FWIW the plot *does* change and the XHR requests to the `timeseries` API call are being made correctly, so I assume that the problem is just in the Selector rendering.

**Comment by corviday** [comment]
Argh, I see what happened. I think I fixed this in DataController, but _not_ in DualDataController.
