### ISSUE TITLE
0.0 data value is treated as "no data" by chart.timeseriesToTimeseriesGraph()

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#92]
`chart.timeseriesToTimeseriesGraph()` was written to graph timeseries of different resolution (IE, monthly vs yearly) or starting and stopping at different times together for comparison graphs by putting a gap in the timeseries line when data is missing.

This functionality is being incorrectly invoked in cases where timeseries data is _present_, but equal to 0.0. Suspect bug in the "missing data" check, using falsiness instead of specifically checking for `undefined` data.

**Example:**
![screenshot from 2017-11-09 12-26-13](https://user-images.githubusercontent.com/4512605/32628346-644d59e2-c54a-11e7-901e-069cf31a25e7.png)

generated from this query:
```JSON
{
  "id": "altwsdiETCCDI_yr_BCCAQ_CNRM-CM5_historical-rcp45_r1i1p1_19500702-21000702",
  "units": "days",
  "data": {
    "1950-07-02T00:00:00Z": 13.189655172413794,
    "1951-07-02T00:00:00Z": 24.84459140292867,
    "1952-07-01T12:00:00Z": 2.7390174775625886,
    "1953-07-02T00:00:00Z": 4.577231931979216,
    "1954-07-02T00:00:00Z": 13.4031648559282,
    "1955-07-02T00:00:00Z": 4.686584789796882,
    "1956-07-01T12:00:00Z": 4.0871516296646195,
    "1957-07-02T00:00:00Z": 8.78814359943316,
    "1958-07-02T00:00:00Z": 2.188946622579121,
    "1959-07-02T00:00:00Z": 0,
    "1960-07-01T12:00:00Z": 14.068965517241379,
    "1961-07-02T00:00:00Z": 4.674539442607464,
    "1962-07-02T00:00:00Z": 0,
    "1963-07-02T00:00:00Z": 20.087387812942843,
    "1964-07-01T12:00:00Z": 0,
    "1965-07-02T00:00:00Z": 5.983230987246103,
    "1966-07-02T00:00:00Z": 15.426310817194143,
    "1967-07-02T00:00:00Z": 3.3434104865375533,
    "1968-07-01T12:00:00Z": 3.2673594709494567,
    "1969-07-02T00:00:00Z": 0,
    "1970-07-02T00:00:00Z": 10.03566367501181,
```

**Comment by corviday** [comment]
This bug probably also exists in `chart.dataToLongTermAverageGraph()`, which has similar handling of missing data.

**Comment by jameshiebert** [comment]
Good catch!
