### ISSUE TITLE
Handle files with differing spatial extents

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#95]
There are a couple dozen files in the `all_downscale_files` ensemble that seem to be cropped versions (the southern half of BC) of other files (all Canada or worldwide). This results in some non-intuitive interactions likely to confuse users, to whom the spatial extent of a file is not displayed except when mapping:

- The full sized file and the cropped file have separate entries in the statistics table, with identical run and date information, but different values
- Both files will be available to display in map and graph dropdowns, but their user-visible metadata is identical (same dates, run, variable, scenario, and model)
- timeseries graph loads one of the datasets arbitrarily and does not let the user pick which one (doesn't have a dataset dropdown)
- Possible to select all-Canada dataset  to display on one graph but South-BC-only on others and not know it, because their displayed metadata is identical.

**Less confusing user option 1: Provide the user enough information to understand when they're working with a South-BC-only dataset**
 - Work out a way to describe a dataset's spatial extent breifly (total square kilometers? centroid? bounding box?), and either have the frontend derive it from the `metadata` query or have the backend supply it with the `multimeta` query. Include it in dropdowns whenever there are multiple datasets of varying spatial coverage so the user can see which one they're working with. Add a dataset dropdown to the timeseries graph.

**Less confusing user option 2: Hide the South-BC-only datasets from the user**
- start a new BC-coverage ensemble, transfer all the cropped data sets into it, in the future maybe display them with the `BCMap` component
- or have Climate Explorer run the `metadata` query any time the parameters a user specifies describe multiple datasets with the same temporal but different spatial coverages. Select a heuristic (widest coverage? most grid squares? highest resolution?) to select a "canonical" dataset with those attributes and consistently display it.

**Comment by rod-glover** [comment]
@corviday please comment here about current status

**Comment by corviday** [comment]
The issues caused by two files that matched in variable, model, run, emissions scenario, and temporal extent but not spatial extent were solved simply by removing the BC-only file from each pair.

We now have some BC-only data that does not replicate Canada-wide data (return period and degree day data), and it works well. 

So this is not, at present, an issue.
